### ISSUE TITLE
Random error message

### ISSUE THREAD

**Issue by ofadam** [jketterl/openwebrx#123]
I'm receiving the following random errors while running openwebrx - voice works just great, but it seems that the scheduled data decoding may not be functioning? Is this related?

```
2020-05-27 00:45:47,791 - owrx.service - DEBUG - re-scheduling services due to sdr changes
2020-05-27 00:45:47,794 - csdr.csdr - DEBUG - dsp thread ended with rc=-15
nmux: signal 15 caught, exiting...
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2020-05-27 00:45:47,794 - owrx.service.schedule - DEBUG - source seems to be idle, selecting profile for background services
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/agerik/openwebrx/csdr/csdr.py", line 57, in copy
    data = read()
  File "/home/agerik/openwebrx/owrx/audio.py", line 242, in read
    return [r.recv() for r in readers]
  File "/home/agerik/openwebrx/owrx/audio.py", line 242, in <listcomp>
    return [r.recv() for r in readers]
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 248, in recv
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/agerik/openwebrx/csdr/csdr.py", line 57, in copy
    data = read()
  File "/home/agerik/openwebrx/owrx/audio.py", line 242, in read
    return [r.recv() for r in readers]
  File "/home/agerik/openwebrx/owrx/audio.py", line 242, in <listcomp>
    return [r.recv() for r in readers]
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 248, in recv
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

**Comment by jketterl** [comment]
this is just a more recent version of #22 - it's been in there for a while now, but hasn't caused any real issues, at least to my knowledge. It only occurs on band changes, when the background services are shutdown and cannot send their final results anywhere.
