### ISSUE TITLE
Reload current page Error

### ISSUE THREAD

**Issue by cyberkrel** [jketterl/openwebrx#145]
```
OpenWebRX - Open Source SDR Web App for Everyone!  | for license see LICENSE file in the package
_________________________________________________________________________________________________

Author contact info:    Jakob Ketterl, DD5JFK <dd5jfk@darc.de>
Documentation:          https://github.com/jketterl/openwebrx/wiki
Support and info:       https://groups.io/g/openwebrx


2020-07-04 22:25:57,207 - owrx.__main__ - INFO - OpenWebRX version v0.19.1 starting up...
2020-07-04 22:25:57,506 - owrx.sdr - INFO - SDR sources loaded. Available SDRs: RTL-SDR USB Stick, Airspy HF+, SDRPlay RSPdx
2020-07-04 22:26:02,203 - owrx.connection - DEBUG - client connection intitialized
2020-07-04 22:26:02,225 - owrx.source - DEBUG - activating profile 70cm
2020-07-04 22:26:02,234 - owrx.source - DEBUG - activating profile 20m
2020-07-04 22:26:02,241 - owrx.source - DEBUG - activating profile 20m
2020-07-04 22:26:03,284 - owrx.source - INFO - Started sdr source: rtl_connector -P 0 -s 2400000 -g 30 -f 438800000 -p 42199 -c 37943
No supported devices found.
no device found.
2020-07-04 22:26:03,296 - owrx.source - DEBUG - shut down with RC=1
2020-07-04 22:26:03,386 - owrx.source.connector - DEBUG - opening control socket...
2020-07-04 22:26:03,388 - owrx.source - ERROR - Exception during postStart()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/source/__init__.py", line 195, in start
    self.postStart()
  File "/usr/lib/python3/dist-packages/owrx/source/connector.py", line 52, in postStart
    self.controlSocket.connect(("localhost", self.controlPort))
ConnectionRefusedError: [Errno 111] Connection refused
2020-07-04 22:26:03,390 - owrx.dsp - DEBUG - received STATE_FAILED, shutting down DspSource
2020-07-04 22:26:03,391 - owrx.connection - WARNING - SDR device "RTL-SDR USB Stick" has failed, selecing new device
2020-07-04 22:26:04,456 - owrx.source - INFO - Started sdr source: soapy_connector -P 0 -s 384000 -g auto -f 14150000 -p 51779 -c 50537 -d driver=airspyhf
SoapySDRDevice_make failed
2020-07-04 22:26:04,554 - owrx.source - DEBUG - shut down with RC=1
2020-07-04 22:26:04,559 - owrx.source.connector - DEBUG - opening control socket...
2020-07-04 22:26:04,560 - owrx.source - ERROR - Exception during postStart()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/source/__init__.py", line 195, in start
    self.postStart()
  File "/usr/lib/python3/dist-packages/owrx/source/connector.py", line 52, in postStart
    self.controlSocket.connect(("localhost", self.controlPort))
ConnectionRefusedError: [Errno 111] Connection refused
2020-07-04 22:26:04,562 - owrx.dsp - DEBUG - received STATE_FAILED, shutting down DspSource
2020-07-04 22:26:04,563 - owrx.connection - WARNING - SDR device "Airspy HF+" has failed, selecing new device
2020-07-04 22:26:05,614 - owrx.source - INFO - Started sdr source: soapy_connector -a "Antenna B" -P 0 -s 500000 -g auto -f 14150000 -p 55037 -c 47355 -d driver=sdrplay -t biasT_ctrl=True
[INFO] devIdx: 0
[INFO] hwVer: 4
IQ worker thread started
setting up control socket...
socket setup complete, waiting for connections
control socket started on 47355
[INFO] Using format CS16.
client connection establised
2020-07-04 22:26:05,820 - owrx.source.connector - DEBUG - opening control socket...
control connection established
2020-07-04 22:26:05,821 - owrx.dsp - DEBUG - received STATE_RUNNING, attempting DspSource restart
2020-07-04 22:26:05,835 - owrx.bands - WARNING - Frequency for wspr on 4m is not within band limits: 70091000
2020-07-04 22:26:05,847 - owrx.fft - DEBUG - Spectrum thread initialized successfully.
2020-07-04 22:26:05,848 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 55037 | csdr fft_cc 4096 2923.9766081871344 | csdr logaveragepower_cf -70 4096 19 | csdr fft_exchange_sides_ff 4096 | csdr compress_fft_adpcm_f_u8 4096
client connection establised
Connection to 127.0.0.1 55037 port [tcp/*] succeeded!
closing client socket
2020-07-04 22:26:09,045 - csdr.csdr - DEBUG - Command = nc -v 127.0.0.1 55037 | csdr shift_addfast_cc --fifo /tmp/openwebrx/openwebrx_pipe_1970264272_shift_pipe | csdr fir_decimate_cc 41 0.0036585365853658534 HAMMING | csdr bandpass_fir_fft_cc --fifo /tmp/openwebrx/openwebrx_pipe_1970264272_bpf_pipe 0.02624 HAMMING | csdr squelch_and_smeter_cc --fifo /tmp/openwebrx/openwebrx_pipe_1970264272_squelch_pipe --outfifo /tmp/openwebrx/openwebrx_pipe_1970264272_smeter_pipe 5 2 | csdr realpart_cf | csdr fractional_decimator_ff 1.016260162601626 | csdr agc_ff | csdr limit_ff | csdr convert_f_s16 | csdr encode_ima_adpcm_i16_u8
2020-07-04 22:26:09,057 - owrx.dsp - DEBUG - adding new output of type audio
csdr shift_addfast_cc: fifo control mode on
2020-07-04 22:26:09,063 - owrx.dsp - DEBUG - adding new output of type smeter
client connection establised
fir_decimate_cc: taps_length = 1093
csdr fir_decimate_cc: taps_length = 1093
csdr fir_decimate_cc: padded_taps_length = 1096
csdr fir_decimate_cc: taps = f8f168
csdr fir_decimate_cc: NEON aligned taps = f8f180
csdr bandpass_fir_fft_cc: fifo control mode on
Connection to 127.0.0.1 55037 port [tcp/*] succeeded!
csdr squelch_and_smeter_cc: fifo control mode on
csdr shift_addfast_cc: reinitialized to 0.16
csdr fractional_decimator_ff: use_prefilter = 0, num_poly_points = 12, transition_bw = 0.03, window = HAMMING
csdr fractional_decimator_ff: not using taps
csdr bandpass_fir_fft_cc: (fft_size = 512) = (taps_length = 153) + (input_size = 360) - 1
(overlap_length = 152) = taps_length - 1
csdr squelch_and_smeter_cc: initial squelch level is 1e-15
csdr bandpass_fir_fft_cc: filter initialized, low_cut = 0.0246, high_cut = 0.246
2020-07-04 22:26:26,643 - owrx.websocket - DEBUG - websocket close frame received; closing connection
2020-07-04 22:26:26,644 - owrx.websocket - DEBUG - websocket loop ended; shutting down
2020-07-04 22:26:26,650 - csdr.csdr - DEBUG - dsp thread ended with rc=-15
signal 15 caught
2020-07-04 22:26:26,658 - csdr.csdr - DEBUG - dsp thread ended with rc=-15
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/csdr/csdr.py", line 61, in copy
    write(data)
  File "/usr/lib/python3/dist-packages/owrx/connection.py", line 290, in write_dsp_data
    self.send(bytes([0x02]) + data)
  File "/usr/lib/python3/dist-packages/owrx/connection.py", line 44, in send
    self.conn.send(data)
  File "/usr/lib/python3/dist-packages/owrx/websocket.py", line 105, in send
    raise WebSocketClosed()
owrx.websocket.WebSocketClosed

2020-07-04 22:26:26,670 - owrx.source - DEBUG - shut down with RC=0
2020-07-04 22:26:26,672 - owrx.cpu - DEBUG - cpu usage thread shut down
2020-07-04 22:26:26,673 - owrx.websocket - DEBUG - websocket loop ended; sending close frame
2020-07-04 22:26:27,148 - owrx.connection - DEBUG - client connection intitialized
2020-07-04 22:26:28,399 - owrx.source - INFO - Started sdr source: soapy_connector -a "Antenna B" -P 0 -s 500000 -g auto -f 14150000 -p 55037 -c 47355 -d driver=sdrplay -t biasT_ctrl=True
[WARNING] Can't find label in args
SoapySDRDevice_make failed
2020-07-04 22:26:28,500 - owrx.source - DEBUG - shut down with RC=1
2020-07-04 22:26:28,602 - owrx.source.connector - DEBUG - opening control socket...
2020-07-04 22:26:28,603 - owrx.source - ERROR - Exception during postStart()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/source/__init__.py", line 195, in start
    self.postStart()
  File "/usr/lib/python3/dist-packages/owrx/source/connector.py", line 52, in postStart
    self.controlSocket.connect(("localhost", self.controlPort))
ConnectionRefusedError: [Errno 111] Connection refused
2020-07-04 22:26:28,604 - owrx.dsp - DEBUG - received STATE_FAILED, shutting down DspSource
2020-07-04 22:26:28,605 - owrx.connection - WARNING - SDR device "SDRPlay RSPdx" has failed, selecing new device
2020-07-04 22:26:28,606 - owrx.connection - WARNING - no more SDR devices available
2020-07-04 22:26:30,399 - owrx.property - ERROR - unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/property/__init__.py", line 78, in _fireCallbacks
    c.call(name, value)
  File "/usr/lib/python3/dist-packages/owrx/property/__init__.py", line 17, in call
    self.subscriber(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/owrx/dsp.py", line 73, in set_dial_freq
    freq = self.props["center_freq"] + self.props["offset_freq"]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2020-07-04 22:26:45,275 - owrx.websocket - DEBUG - websocket close frame received; closing connection
2020-07-04 22:26:45,276 - owrx.websocket - DEBUG - websocket loop ended; shutting down
2020-07-04 22:26:45,278 - owrx.cpu - DEBUG - cpu usage thread shut down
2020-07-04 22:26:45,280 - owrx.websocket - DEBUG - websocket loop ended; sending close frame
2020-07-04 22:26:45,743 - owrx.connection - DEBUG - client connection intitialized
2020-07-04 22:26:45,750 - owrx.connection - WARNING - no more SDR devices available
2020-07-04 22:26:47,770 - owrx.connection - WARNING - DSP not available; discarding client data
```

**Comment by cyberkrel** [comment]
RSPdx problem resolved
----------------------------------
always-on

Optional key. Can be used to force continuous operation of the SDR device. Useful if the device startup is unreliable or unreproducible.

Boolean option. Set to True or False (first letter uppercase is mandatory).

-----------------------------------
Thank you!
