### ISSUE TITLE
Python3 version support

### ISSUE THREAD

**Issue by vk4tux** [jketterl/openwebrx#295]
Runnning debian bookworm/sid I get ;

adrian@debian:~/Downloads/openwebrx$ ./openwebrx.py
Traceback (most recent call last):
  File "/home/adrian/Downloads/openwebrx/./openwebrx.py", line 3, in <module>
    from owrx.__main__ import main
  File "/home/adrian/Downloads/openwebrx/owrx/__main__.py", line 8, in <module>
    from owrx.http import RequestHandler
  File "/home/adrian/Downloads/openwebrx/owrx/http.py", line 1, in <module>
    from owrx.controllers.status import StatusController
  File "/home/adrian/Downloads/openwebrx/owrx/controllers/status.py", line 3, in <module>
    from owrx.sdr import SdrService
  File "/home/adrian/Downloads/openwebrx/owrx/sdr.py", line 4, in <module>
    from owrx.source import SdrSource, SdrSourceEventClient
  File "/home/adrian/Downloads/openwebrx/owrx/source/__init__.py", line 24, in <module>
    from pycsdr.modules import TcpSource, Buffer
ModuleNotFoundError: No module named 'pycsdr'
adrian@debian:~/Downloads/openwebrx$ 

or

adrian@debian:~/Downloads/openwebrx$ sudo apt install openwebrx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-csdr : Depends: python3 (< 3.10) but 3.10.4-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
adrian@debian:~/Downloads/openwebrx$

**Comment by jketterl** [comment]
Please use the issue template when reporting an issue.

Please use the mailing list when requesting general support.
