### ISSUE TITLE
usb_open_error -4 rtl-sdr nesdr smart v5

### ISSUE THREAD

**Issue by mikepaxton** [jketterl/openwebrx#379]
When I start openwebrx using docker compose up, I get some error messages stating it's unable to find/open the usb device.  usb_open_error -4 

I installed the latest dev version, v1.3.0-dev using docker compose.  This is running on a Raspberry Pi 5, PiOS kernel 6.1.0-rpi8-rpi-2712 .  I've installed the rtl-sdr driver using apt install rtl-sdr.  rtl_test comes back good, it sees it.
I've blacklisted the device as documented in the wiki.

For a test I flashed an sd card using the latest experimental bookworm image, it worked like a charm.  I did notice the image doesn't have the rtl-sdr blacklisted, so I tried removing that with no luck.

Here is a copy of the log upon startup.

2024-03-17 00:05:13,542 - owrx.config.migration - DEBUG - migrating config from version 1
2024-03-17 00:05:13,563 - owrx.__main__ - INFO - Ready to serve requests.
2024-03-17 00:05:14,606 - owrx.connection - DEBUG - client connection initialized
2024-03-17 00:05:14,607 - owrx.connection - DEBUG - handshake complete, handing off to OpenWebRxReceiverClient
2024-03-17 00:05:14,612 - owrx.source.rtlsdr - INFO - Started sdr source: rtl_connector -g 25.4 -s 2048000 -f 145000000 -p 39287 -c 50521
2024-03-17 00:05:14,614 - owrx.source.rtlsdr - INFO - STDOUT: setting up control socket...
2024-03-17 00:05:14,615 - owrx.source.rtlsdr - INFO - STDOUT: control socket started on 50521
2024-03-17 00:05:14,615 - owrx.source.rtlsdr - INFO - STDOUT: socket setup complete, waiting for connections
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/openwebrx/owrx/log/__init__.py", line 22, in run
    for line in iter(self.pipeReader.readline, ''):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 26: invalid start byte
2024-03-17 00:05:14,655 - owrx.source.rtlsdr - WARNING - STDERR: usb_open error -4
2024-03-17 00:05:14,655 - owrx.source.rtlsdr - WARNING - STDERR: device could not be opened
2024-03-17 00:05:14,655 - owrx.source.rtlsdr - WARNING - STDERR: Connector::open() failed
2024-03-17 00:05:14,655 - owrx.source.rtlsdr - DEBUG - shut down with RC=1
2024-03-17 00:05:14,713 - owrx.source.rtlsdr - DEBUG - opening control socket...
2024-03-17 00:05:14,715 - owrx.source.rtlsdr - ERROR - Exception during postStart()
Traceback (most recent call last):
  File "/opt/openwebrx/owrx/source/__init__.py", line 374, in start
    self.postStart()
  File "/opt/openwebrx/owrx/source/connector.py", line 57, in postStart
    self.controlSocket.connect(("localhost", self.controlPort))
ConnectionRefusedError: [Errno 111] Connection refused
2024-03-17 00:05:14,718 - owrx.connection - WARNING - SDR device "RTL-SDR USB Stick" has failed, selecting new device
2024-03-17 00:05:14,719 - owrx.connection - WARNING - no more SDR devices available
2024-03-17 00:05:16,184 - owrx.cpu - DEBUG - cpu usage thread starting up

I should note, I tried posting this on openwebrx@groups.io, for whatever reason I'm not seeing that it go posted.  So I'm posting it here, sorry if this ends up being a duplicate on groups.io.

I'm sure this is something simple that i'm overlooking but I can't figure it out.

**Comment by jketterl** [comment]
Please use the issue template.
Please use the mailing list for support requests.

The mailing list is moderated, and your messages are currently in the moderation queue. Please have some patience...
